module.exports = {
    badgesFromDisc: [
        {
            name: 'ActiveDeveloper',
            description:
                'User is an active developer. https://discord.com/developers/active-developer',
            shift: 22,
            undocumented: false,
            image: './img/disc_activ_dev.png',
            emoji: '<:disc_activ_dev:1041783917021249538>',
        },
        {
            name: 'BotHTTPInteractions',
            description: 'Bot is an HTTP interaction.',
            shift: 19,
            undocumented: false,
            image: './img/disc_bot_http.png',
            emoji: '<:disc_bot_http:1041901711796744263>',
        },
        {
            name: 'BugHunterLevel1',
            description: 'User is a Bug Hunter.',
            shift: 3,
            undocumented: false,
            image: './img/disc_bug_h1.png',
            emoji: '<:disc_bug_h1:1041783920611561572>',
        },
        {
            name: 'BugHunterLevel2',
            description: 'User has the gold Bug Hunter badge.',
            shift: 14,
            undocumented: false,
            image: './img/disc_bug_h2.png',
            emoji: '<:disc_bug_h2:1041783922125713509>',
        },
        {
            name: 'CertifiedModerator',
            description: 'User is a Discord certified moderator.',
            shift: 18,
            undocumented: false,
            image: './img/disc_mod.png',
            emoji: '<:disc_mod:1041783933341282385>',
        },
        {
            name: 'HypeSquadOnlineHouse1',
            description: 'User is part of HypeSquad Bravery.',
            shift: 6,
            undocumented: false,
            image: './img/disc_hype_brave.png',
            emoji: '<:disc_hype_brave:1041783927666393148>',
        },
        {
            name: 'HypeSquadOnlineHouse2',
            description: 'User is part of HypeSquad Brilliance.',
            shift: 7,
            undocumented: false,
            image: './img/disc_hype_brill.png',
            emoji: '<:disc_hype_brill:1041783929063084122>',
        },
        {
            name: 'HypeSquadOnlineHouse3',
            description: 'User is a part of HypeSquad Balance.',
            shift: 8,
            undocumented: false,
            image: './img/disc_hype_balan.png',
            emoji: '<:disc_hype_balan:1041783926215147580>',
        },
        {
            name: 'Hypesquad',
            description: 'User is a HypeSquad Events member.',
            shift: 2,
            undocumented: false,
            image: './img/disc_hype.png',
            emoji: '<:disc_hype:1041783924860387458>',
        },
        {
            name: 'Partner',
            description: 'User is a Discord partner.',
            shift: 1,
            undocumented: false,
            image: './img/png/disc_partner.png',
            emoji: '<:disc_partner:1041783934884790363>',
        },
        {
            name: 'PremiumEarlySupporter',
            description: 'User is an Early Supporter.',
            shift: 9,
            undocumented: false,
            image: './img/disc_early_sup.png',
            emoji: '<:disc_early_sup:1041783923480477707>',
        },
        {
            name: 'Staff',
            description: 'User is a Discord employee.',
            shift: 0,
            undocumented: false,
            image: './img/disc_staff.svg',
            emoji: '<:disc_staff:1041783936369561761>',
        },
        {
            name: 'TeamPseudoUser',
            description: 'Account is a Team account.',
            shift: 10,
            undocumented: false,
            image: './img/disc_team.png',
            emoji: '<:disc_team:1041901713344450560>',
        },
        {
            name: 'VerifiedBot',
            description: 'User is a verified bot.',
            shift: 16,
            undocumented: false,
            image: './img/disc_ver_bot.png',
            emoji: '<:disc_ver_bot:1041901714808254565>',
        },
        {
            name: 'VerifiedDeveloper',
            description: 'User is a verified bot developer.',
            shift: 17,
            undocumented: false,
            image: './img/disc_bot_dev.png',
            emoji: '<:disc_bot_dev:1041783918564741120>',
        },
    ],
}
